"use client";

import React, { useState, useMemo } from 'react';
import { MilkEntry } from '@/lib/types';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Button } from '@/components/ui/button';
import { Calculator, Calendar, Droplets, Banknote, History, MessageCircle } from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { formatDate } from '@/lib/utils';

interface SmartHisabProps {
  customerName: string;
  phoneNumber?: string;
  entries: MilkEntry[];
  sellerName: string;
}

export default function SmartHisab({ customerName, phoneNumber, entries, sellerName }: SmartHisabProps) {
  const [fromDate, setFromDate] = useState(() => {
    const d = new Date();
    d.setDate(1); // Default to start of current month
    return d.toISOString().split('T')[0];
  });
  const [toDate, setToDate] = useState(new Date().toISOString().split('T')[0]);

  const stats = useMemo(() => {
    const filtered = entries.filter(e => e.date >= fromDate && e.date <= toDate);
    
    const totalLiters = filtered.reduce((sum, e) => sum + e.milkQuantity, 0);
    const totalAmount = filtered.reduce((sum, e) => sum + e.total, 0);
    const totalPaid = filtered.filter(e => e.paid).reduce((sum, e) => sum + e.total, 0);
    const totalDue = filtered.filter(e => !e.paid).reduce((sum, e) => sum + e.total, 0);
    const entryCount = filtered.length;

    return { totalLiters, totalAmount, totalPaid, totalDue, entryCount, filtered };
  }, [entries, fromDate, toDate]);

  const handleShareHisab = () => {
    const text = `*📊 SMART HISAB SUMMARY*\n` +
                 `*Seller:* ${sellerName}\n` +
                 `*Customer:* ${customerName}\n` +
                 `*Period:* ${formatDate(fromDate)} to ${formatDate(toDate)}\n` +
                 `--------------------------\n` +
                 `*Total Volume:* ${stats.totalLiters.toFixed(2)} L\n` +
                 `*Total Amount:* ₹${stats.totalAmount.toFixed(2)}\n` +
                 `*Received:* ₹${stats.totalPaid.toFixed(2)}\n` +
                 `--------------------------\n` +
                 `*PENDING DUE: ₹${stats.totalDue.toFixed(2)}*\n` +
                 `--------------------------\n` +
                 `Generated by Milk Tracker Pro`;

    const phone = phoneNumber?.replace(/\D/g, '');
    const waUrl = `https://wa.me/${phone}?text=${encodeURIComponent(text)}`;
    window.open(waUrl, '_blank');
  };

  return (
    <div className="space-y-6 animate-in fade-in slide-in-from-bottom-2">
      <Card className="border-primary/20 bg-primary/5">
        <CardHeader>
          <div className="flex items-center gap-2">
            <Calculator className="h-5 w-5 text-primary" />
            <div>
              <CardTitle>Smart Hisab Calculator</CardTitle>
              <CardDescription>Calculate totals for any custom date range</CardDescription>
            </div>
          </div>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label htmlFor="hisab-from">From Date</Label>
              <Input 
                id="hisab-from" 
                type="date" 
                value={fromDate} 
                onChange={e => setFromDate(e.target.value)} 
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="hisab-to">To Date</Label>
              <Input 
                id="hisab-to" 
                type="date" 
                value={toDate} 
                onChange={e => setToDate(e.target.value)} 
              />
            </div>
          </div>
        </CardContent>
      </Card>

      <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
        <Card className="bg-blue-500/5 border-blue-500/20">
          <CardContent className="pt-6 flex flex-col items-center justify-center text-center">
            <Droplets className="h-5 w-5 text-blue-500 mb-2" />
            <p className="text-[10px] font-bold uppercase text-muted-foreground">Total Milk</p>
            <p className="text-xl font-black text-blue-700">{stats.totalLiters.toFixed(1)} L</p>
          </CardContent>
        </Card>
        
        <Card className="bg-emerald-500/5 border-emerald-500/20">
          <CardContent className="pt-6 flex flex-col items-center justify-center text-center">
            <Banknote className="h-5 w-5 text-emerald-500 mb-2" />
            <p className="text-[10px] font-bold uppercase text-muted-foreground">Total Bill</p>
            <p className="text-xl font-black text-emerald-700">₹{stats.totalAmount.toFixed(0)}</p>
          </CardContent>
        </Card>

        <Card className="bg-red-500/5 border-red-500/20">
          <CardContent className="pt-6 flex flex-col items-center justify-center text-center">
            <History className="h-5 w-5 text-red-500 mb-2" />
            <p className="text-[10px] font-bold uppercase text-muted-foreground">Total Due</p>
            <p className="text-xl font-black text-red-700">₹{stats.totalDue.toFixed(0)}</p>
          </CardContent>
        </Card>

        <Card className="bg-slate-500/5 border-slate-500/20">
          <CardContent className="pt-6 flex flex-col items-center justify-center text-center">
            <Calendar className="h-5 w-5 text-slate-500 mb-2" />
            <p className="text-[10px] font-bold uppercase text-muted-foreground">Deliveries</p>
            <p className="text-xl font-black text-slate-700">{stats.entryCount}</p>
          </CardContent>
        </Card>
      </div>

      <Card>
        <CardHeader className="pb-3">
          <div className="flex justify-between items-center">
            <CardTitle className="text-sm font-bold uppercase tracking-tight">Period Breakdown</CardTitle>
            <Button 
              size="sm" 
              onClick={handleShareHisab} 
              className="bg-emerald-600 hover:bg-emerald-700 gap-2"
              disabled={stats.entryCount === 0}
            >
              <MessageCircle className="h-4 w-4" /> Share on WhatsApp
            </Button>
          </div>
        </CardHeader>
        <CardContent className="p-0">
          <div className="divide-y max-h-[300px] overflow-auto">
            {stats.filtered.length === 0 ? (
              <div className="py-10 text-center text-muted-foreground italic text-sm">
                No records found for this period.
              </div>
            ) : (
              stats.filtered.sort((a,b) => b.date.localeCompare(a.date)).map(e => (
                <div key={e.id} className="flex items-center justify-between p-3 px-6 hover:bg-muted/30 transition-colors">
                  <div className="flex flex-col">
                    <span className="font-bold text-sm">{formatDate(e.date)}</span>
                    <span className="text-[10px] text-muted-foreground">{e.timeOfDay}</span>
                  </div>
                  <div className="flex items-center gap-6">
                    <div className="text-right">
                      <p className="text-sm font-bold">{e.milkQuantity}L</p>
                      <p className="text-[10px] text-muted-foreground">₹{e.price}/L</p>
                    </div>
                    <div className="w-20 text-right">
                      <p className="text-sm font-black">₹{e.total.toFixed(2)}</p>
                      <Badge variant="outline" className={`text-[8px] uppercase px-1 h-4 leading-none ${e.paid ? 'border-emerald-200 text-emerald-600' : 'border-red-200 text-red-600'}`}>
                        {e.paid ? 'Paid' : 'Due'}
                      </Badge>
                    </div>
                  </div>
                </div>
              ))
            )}
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
